Repository Hunter87ff/Spruce, pull requests merged in 2025-05, with the labels that each got.

#60 Development
  requirements.txt
  src/core/moderation.py
  src/core/tourney.py
  src/main.py
Labels: bug, documentation, enhancement

#68 Update tourney.py
  src/core/tourney.py
Labels: bug

#69 Filter out bots from the mentions of team registration
  src/modules/message_handle.py
Labels: bug, enhancement

#71 Fixed invalid interaction handling, improve few event managing view and readability
  src/core/tourney.py
  src/main.py
Labels: bug, documentation, enhancement

#74 Add teams command to dev cog and enhance tourney permissions checks
  src/core/dev.py
  src/core/tourney.py
  src/ext/__init__.py
  src/ext/modals.py
  src/ext/permissions.py
Labels: bug, enhancement, dependencies

#75 Updated tournament wrapper for better readability and centralization and configured new view based registration
  src/core/tourney.py
  src/ext/modals.py
  src/modules/message_handle.py
Labels: bug, documentation, enhancement, feature request

#76 Refactor permission checks for tournament moderator role and streamli…
  src/core/tourney.py
  src/ext/permissions.py
Labels: enhancement

#78 Updated Cog integration, disabled overall music module and it's depen…
  .github/workflows/py_application.yml
  src/cogs/__init__.py
  src/cogs/channel.py
  src/cogs/dev.py
  src/cogs/helpcog.py
  src/cogs/moderation.py
  src/cogs/music.py
  src/cogs/role.py
  src/cogs/scrim.py
  src/cogs/tasks.py
  src/cogs/tourney.py
  src/cogs/utility.py
  src/ext/db.py
  src/ext/logger.py
  src/main.py
  src/modules/.env-example
  src/modules/bot.py
  src/modules/chat.py
  src/modules/config.py
  test/test.py
Labels: bug, documentation, enhancement, dependencies

#79 Refactors the codebase to standardize environment variable naming conventions. and overall optimization
  .github/workflows/py_application.yml
  README.md
  src/cogs/__init__.py
  src/cogs/channel.py
  src/cogs/helpcog.py
  src/cogs/moderation.py
  src/cogs/music.py
  src/cogs/role.py
  src/cogs/scrim.py
  src/cogs/tasks.py
  src/cogs/tourney.py
  src/cogs/utility.py
  src/ext/__init__.py
  src/ext/error.py
  src/ext/helper.py
  src/ext/logger.py
  src/main.py
  src/modules/bot.py
  src/modules/chat.py
  src/modules/config.py
Labels: bug, enhancement

#80 refactor: improve database configuration handling and logging
  src/ext/db.py
  src/main.py
  src/modules/.env-example
  src/modules/chat.py
  src/modules/config.py
  src/modules/payment.py
Labels: bug, documentation, enhancement

#81 updated Configurations, Databse and error handlers
  pyproject.toml
  src/ext/db.py
  src/main.py
  src/modules/chat.py
  src/modules/config.py
  src/modules/payment.py
  uv.lock
Labels: bug, documentation, dependencies

#86 Enhance tourney logging functionality and permissions management; add setup command for tourney log channel
  src/cogs/tourney.py
  src/ext/helper.py
  src/modules/message_handle.py
Labels: bug, documentation, enhancement

#90 feat(scrim): Enhance scrim management with new commands and features, updated tourneys list criteria
  src/cogs/scrim.py
  src/cogs/tourney.py
  src/cogs/utility.py
  src/ext/error.py
  src/ext/models/scrim.py
  src/ext/permissions.py
  src/ext/time.py
  src/modules/message_handle.py
Labels: documentation, enhancement, feature
